const FETCH_DATA_REQUEST = 'SWAPI/FETCH_DATA_REQUEST'
const FETCH_DATA_SUCCES = 'SWAPI/FETCH_DATA_SUCCES'
const FETCH_DATA_FAILURE = 'SWAPI/FETCH_DATA_FAILURE'

export {
    FETCH_DATA_FAILURE,
    FETCH_DATA_REQUEST,
    FETCH_DATA_SUCCES
}